services:
  - type: web
    name: discord-loan-bot
    env: python
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    # Run the token validation script first, then use setup_render.py
    startCommand: |
      python test_token.py && python setup_render.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: UNBELIEVABOAT_API_KEY
        sync: false
      - key: CLIENT_ID
        sync: false 