services:
  - type: web
    name: discord-loan-bot
    env: python
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    # Run the token validation script first, then start the server
    startCommand: |
      python test_token.py && python server.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: UNBELIEVABOAT_API_KEY
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    # Add explicit port configuration
    ports:
      - port: 10000
        protocol: http 