services:
  - type: web
    name: discord-loan-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: UNBELIEVABOAT_API_KEY
        sync: false 