services:
  - type: web
    name: discord-loan-bot
    env: python
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    # Use the setup script to ensure all directories exist
    startCommand: python setup_render.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: UNBELIEVABOAT_API_KEY
        sync: false
      - key: CLIENT_ID
        sync: false 